version: '3'
services:
  backend:
    image: jozimar/consulta-medico-back:latest
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    image: jozimar/consulta-medico:latest
    ports:
      - 4200:80
    restart: unless-stopped
    

